name: Society
main: Society\Society
version: 1.0.0
api: 5.0.0
author: syseditor

commands:
  friends:
    description: "Friends command!"
    permission: society.friends

permissions:
  society.friends:
    description: "Default permission to use the /friends command"
    default: true
  society.party:
    description: "Default permission to use the /party command"
    default: true
  society.guild:
    description: "Default permission to use the /guild command"
    default: true
  society.guild.hundred:
    description: "100 members per guild"
    default: op
  society.guild.twohundred:
    description: "200 members per guild"
    default: op
  society.guild.create:
    description: "Permission to create a guild"
    default: op
  society.party.ten:
    description: "Ten members per party"
    default: op
  society.party.twenty:
    description: "Twenty members per party"
    default: op